MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
MYSQL_DATABASE: user
MYSQL_USER: root
MYSQL_PASSWORD: "password"
SERVER_PORT: ":8989"
MYSQL_MAXIDLE: 10
MYSQL_MAXCONN: 100
MYSQL_CONNMAXLIFETTIME: 30
MYSQL_SINGULARTABLE: true
MYSQL_LOGMODE: true
NSQTOPIC:
  topic_1:
    handler: SoloOrder
    topic: SOLO_ORDER_ERROR_TOPIC
    channel: test
    boardcast: false
    ephemeral: true
  topic_2:
    handler: Order
    topic: EDEN_ORDER_CREDIT
    channel: test
    boardcast: false
    ephemeral: true
NSQRECEIVETOPIC_TOPIC_1_HANDLER: SoloOrder
NSQRECEIVETOPIC_TOPIC_1_TOPIC: SOLO_ORDER_ERROR_TOPIC
NSQRECEIVETOPIC_TOPIC_1_CHANNEL: test
NSQRECEIVETOPIC_TOPIC_1_BOARDCAST: false
NSQRECEIVETOPIC_TOPIC_1_EPHEMERAL: true
NSQRECEIVETOPIC_TOPIC_2_HANDLER: Qrder
NSQRECEIVETOPIC_TOPIC_2_TOPIC: EDEN_ORDER_CREDIT
NSQRECEIVETOPIC_TOPIC_2_CHANNEL: test
NSQRECEIVETOPIC_TOPIC_2_BOARDCAST: false
NSQRECEIVETOPIC_TOPIC_2_EPHEMERAL: true
